### ISSUE TITLE
Not sure how to use?

### ISSUE THREAD

**Issue by reagle** [adamarthurryan/dubdiff#10]
I added github as a repo, installed, but see nothing about it in the control panel...?

**Comment by adamarthurryan** [comment]
Hi @reagle, 

This is a fullstack Node.js + Angular app so, assuming you have Node and NPM installed on your local machine, you can type `npm install && bower install` to install the prerequisites and then `grunt serve:dist` to launch the server.

You could also just use the service at (http://dubdiff.com). ;)

Does that work for you?

**Comment by reagle** [comment]
I think you should document on your README that there are other dependencies and requires a server to be run.

**Comment by adamarthurryan** [comment]
You're right, absolutely. I'll add some info about how go set up and run
the software! I'll let you know when it's online.

**Comment by adamarthurryan** [comment]
Well, I had to reboot my server, so that was a good opportunity to simplify the install and document the setup process. (I used Docker before? Why?)
